baseURL: https://creative.clox.nu/
languageCode: en-us
title: cloxnu's Creative Space
theme: "PaperMod"

googleAnalytics: UA-151087524-1
# disqusShortname: clox-nu

publishdir: ../docs/

permalinks:
  posts: /blog/:slug/
  news: /news/:year/:month/:day/:slug/

params:
  env: production
  title: cloxnu's creative space
  description: "Hi, I'm creating more creative works. Here are my thoughts, essays and expectations."
  author: Sidney Liu

  utteranc:
    enable: true
    repo: "cloxnu/creative.clox.nu"
    issueTerm: "pathname"
    theme: "preferred-color-scheme"

  ShowReadingTime: true
  ShowPostNavLinks: true

  assets:
    favicon: "/logo/favicon.ico"
    favicon16x16: "/logo/favicon-16x16.png"
    favicon32x32: "/logo/favicon-32x32.png"
    apple-touch-icon: "/logo/apple-touch-icon-180x180.png"

  label:
    text: "I'm cloxnu"
    icon: "/logo/logo.svg"
    iconHeight: 35

  homeInfoParams:
    Title: "Hi there \U0001F44B"
    Content: >
      Welcome to cloxnu's creative space.

      - ğŸ“– My series of articles:

      - [â„™ğ•£ğ• ğ••ğ•¦ğ•”ğ•¥ğ•šğ•§ğ•šğ•¥ğ•ª](/posts/productivity/) | [The Command Book](https://thecommandbook.clox.nu)

  socialIcons:
    - name: twitter
      url: "https://twitter.com/cloxnu"
    - name: github
      url: "https://github.com/cloxnu"
    - name: mastodon
      url: "https://pawoo.net/@cloxnu"
    - name: rss
      url: "/index.xml"

menu:
  main:
    - identifier: news
      name: ğŸ“° ğ•¹ğ–Šğ–œğ–˜
      url: /news/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 20
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 30
    - identifier: about
      name: About
      url: https://clox.nu
      weight: 40


